<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZadNCnx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZadNCnx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZadNCnx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZadNCnx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZadNCnx\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZadNCnx',
    'container.build_id' => '6d491673',
    'container.build_time' => 1672206710,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZadNCnx');
